<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SelfContained)' == 'true'">
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="TerrariaResearchTracker.cfg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="TerrariaResearchTracker.wld">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <!-- These are .NET Framework dependencies Terraria uses on Windows. They're not in the core libraries in modern .NET -->
    <!-- If TerrariaServer ever fails to find something, try replacing these with Microsoft.Windows.Compatibility -->
    <PackageReference Include="System.IO.Packaging" Version="10.0.11" />
    <PackageReference Include="System.Security.Permissions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TerrariaServer">
      <HintPath>$(TERRARIA_PATH)/TerrariaServer.exe</HintPath>
      <Private>false</Private>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Reference>
  </ItemGroup>

</Project>
