<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>embedded</DebugType>
    <GenerateSupportedRuntime>false</GenerateSupportedRuntime>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="TerrariaResearchTracker.cfg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TerrariaResearchTracker.wld">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TerrariaServer">
      <HintPath>$(TERRARIA_PATH)/TerrariaServer.exe</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>